let activities=[
  {
    id: 101,
    title:"Science",
    location: "London",
    price: 10,
    spaces: 5,
    image: "images/science.jpg",
    rating: 3,
  },
  {
    id: 102,
    title: "English",
    location:  "Dubai",
    price: 5,
    spaces: 5,
    image: "images/english.jpg",
    rating: 5,
  },
  {
    id: 103,
    title: "Art",
    location: "London",
    price: 7.50,
    spaces: 5,
    image: "images/art.jpg",
    rating: 4,
    },
    {
      id: 104,
      title: "ICT",
      location: "Malta",
      price: 8.50,
      spaces: 5,
      image: "images/ict.jpg",
      rating: 2,
    },
    {
      id: 105,
      title: "Math",
      location: "Dubai",
      price: 4.99,
      spaces: 5,
      image: "images/math.jpg",
      rating: 2,
    },
    {
      id: 106,
      title: "French",
      location: "London",
      price: 4,
      spaces: 5,
      image: "images/french.jpg",
      rating: 4,
      },
      {
        id: 107,
        title:  "Physical Education",
        location: "London",
        price: 4,
        spaces: 5,
        image: "images/pe.jpg",
        rating: 4,
      },
      {
        id: 108,
        title: "Geography",
        location: "Dubai",
        price: 3,
        spaces: 5,
        image: "images/geo.jpg",
        rating: 3,
      },
      {
        id: 109,
        title: "History",
        location: "Malta",
        price: 8,
        spaces: 5,
        image: "images/history.jpg",
        rating: 4,
        },
        {
          id: 110,
          title: "Music",
          location: "Dubai",
          price: 30,
          spaces: 5,
          image: "images/music.jpg",
          rating: 1,
        },
]